[package]
name = "cm_macro"
version = "0.0.0"
authors = ["Mingwei Samuel <mingwei.samuel@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.81"
proc-macro-crate = "3.1.0"
quote = "1.0.36"
syn = { version = "2.0.60", features = [ "parsing", "extra-traits" ] }
